#!/bin/bash
NETNAME=test

PARAMS="--rm --cap-add NET_ADMIN --device /dev/net/tun --net=host -e NETNAME=$NETNAME -v $PWD/$NETNAME:/usr/local/etc/tinc/$NETNAME"

if [ $1 == start ]; then
  if [ "$2" == "" ]; then
    echo "Usage tinc start ip_addr/mask"
  else
    docker run -d $PARAMS --name tinc emanaev/tinc tincd -D -d7
    docker logs -f tinc 2>&1| grep -m 1 'Unconfigured tinc-up script, please edit'
    docker run --rm $PARAMS emanaev/tinc ip link set $NETNAME up
    docker run --rm $PARAMS emanaev/tinc ip addr add $2 dev $NETNAME
  fi
else if [ $1 == stop ]; then
    docker stop tinc
  else
    docker run -it --rm $PARAMS emanaev/tinc tinc $*
fi fi

